/*@Generated by SharpKit v4.23.8000*/
if(typeof(Physics) == "undefined")
    Physics = {};
if(typeof(Physics.ForceDissipationFunction) == "undefined")
    Physics.ForceDissipationFunction = {};
Physics.ForceDissipationFunction.IForceDissipationFunction = function()
{
}
