/*@Generated by SharpKit v4.23.8000*/
if (typeof($Inherit)=='undefined') {
    function $Inherit(ce, ce2) {
        for (var p in ce2.prototype)
            if (typeof(ce.prototype[p]) == 'undefined' || ce.prototype[p]==Object.prototype[p])
                ce.prototype[p] = ce2.prototype[p];
        for (var p in ce2)
            if (typeof(ce[p]) == 'undefined')
                ce[p] = ce2[p];
    }
}
if(typeof(Physics) == "undefined")
    Physics = {};
if(typeof(Physics.ForceDissipationFunction) == "undefined")
    Physics.ForceDissipationFunction = {};
Physics.ForceDissipationFunction.InverseDistanceDissipationFunction = function(scaleFactor)
{
    Physics.ForceDissipationFunction.IForceDissipationFunction.call(this);
    this._scaleFactor = scaleFactor;
}
Physics.ForceDissipationFunction.InverseDistanceDissipationFunction.prototype._scaleFactor = 0;
Physics.ForceDissipationFunction.InverseDistanceDissipationFunction.prototype.GetForceAtDistance = function(distance)
{
    if((distance * this._scaleFactor) < 1)
    {
        return 1;
    }
    else
    {
        return 1 / (distance * this._scaleFactor);
    }
}
$Inherit(Physics.ForceDissipationFunction.InverseDistanceDissipationFunction,Physics.ForceDissipationFunction.IForceDissipationFunction);
