/*@Generated by SharpKit v4.23.8000*/
if (typeof($Inherit)=='undefined') {
    function $Inherit(ce, ce2) {
        for (var p in ce2.prototype)
            if (typeof(ce.prototype[p]) == 'undefined' || ce.prototype[p]==Object.prototype[p])
                ce.prototype[p] = ce2.prototype[p];
        for (var p in ce2)
            if (typeof(ce[p]) == 'undefined')
                ce[p] = ce2[p];
    }
}
if(typeof(Physics) == "undefined")
    Physics = {};
if(typeof(Physics.ForceDissipationFunction) == "undefined")
    Physics.ForceDissipationFunction = {};
Physics.ForceDissipationFunction.LinearForceDissipationFunction = function(distanceOfNoEffect)
{
    Physics.ForceDissipationFunction.IForceDissipationFunction.call(this);
    this._distanceOfNoEffect = distanceOfNoEffect;
}
Physics.ForceDissipationFunction.LinearForceDissipationFunction.prototype._distanceOfNoEffect = 0;
Physics.ForceDissipationFunction.LinearForceDissipationFunction.prototype.GetForceAtDistance = function(distance)
{
    if(distance > this._distanceOfNoEffect)
    {
        return 0;
    }
    else
    {
        return (this._distanceOfNoEffect - distance) / this._distanceOfNoEffect;
    }
}
$Inherit(Physics.ForceDissipationFunction.LinearForceDissipationFunction,Physics.ForceDissipationFunction.IForceDissipationFunction);
