/*@Generated by SharpKit v4.23.8000*/
if (typeof($Inherit)=='undefined') {
    function $Inherit(ce, ce2) {
        for (var p in ce2.prototype)
            if (typeof(ce.prototype[p]) == 'undefined' || ce.prototype[p]==Object.prototype[p])
                ce.prototype[p] = ce2.prototype[p];
        for (var p in ce2)
            if (typeof(ce[p]) == 'undefined')
                ce[p] = ce2[p];
    }
}
if(typeof(Physics) == "undefined")
    Physics = {};
Physics.ConnectorMetadata = function()
{
    Physics.PhysicsMetadata.call(this);
}
$Inherit(Physics.ConnectorMetadata,Physics.PhysicsMetadata);
