/*@Generated by SharpKit v4.23.8000*/
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var ForceDissipationDelegate=
{
    fullname:"ForceDissipationDelegate",
    Kind:"Delegate",
    definition:
    {
        ctor:function(obj,func)
        {
            System.MulticastDelegate.ctor.call(this,obj,func);
        }
    }
};
JsTypes.push(ForceDissipationDelegate);
