/*@Generated by SharpKit v4.23.8000*/
if(typeof(Physics) == "undefined")
    Physics = {};
Physics.MetaDataDisposeEventArgs = function(metaData)
{
    this._metaData = metaData;
}
Physics.MetaDataDisposeEventArgs.prototype._metaData = null;
Physics.MetaDataDisposeEventArgs.prototype.get_MetaData = function()
{
    return this._metaData;
}
Physics.MetaDataDisposeEventArgs.prototype.set_MetaData = function(value)
{
    this._metaData = value;
}
