/*@Generated by SharpKit v4.23.8000*/
if(typeof(JsTypes) == "undefined")
    JsTypes = [];
var Physics$MetaDataDisposeHandler=
{
    fullname:"Physics.MetaDataDisposeHandler",
    Kind:"Delegate",
    definition:
    {
        ctor:function(obj,func)
        {
            System.MulticastDelegate.ctor.call(this,obj,func);
        }
    }
};
JsTypes.push(Physics$MetaDataDisposeHandler);
